# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-17 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careertalk',
            name='citycode',
            field=models.CharField(default='1', max_length=128),
            preserve_default=False,
        ),
    ]
