# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-20 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_careertalk_citycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='loccode',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
